on: [push, pull_request]

name: Test and Build

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Verify versions
        run: go version

      - name: Cache build artifacts
        id: cache-go
        uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ${{ env.GOROOT }}
          key: ${{ runner.os }}-go

      - name: Install dependencies
        run: go get

      - name: Build code
        run: go build

      - name: Test code
        run: go test
